from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenRefreshView,
    TokenVerifyView
)

from .views import (
    UserViewSet,
    AddressViewSet,
    PhysicalAddressViewSet,
    CreditCardViewSet,
    LoginView,
    CustomLogoutView,
    OTPViewSet, 
    ChatViewSet,
    MessageViewSet,
    AllChatsViewSet,
)

# Initialize the router to automatically generate URLs for viewsets
router = DefaultRouter()

# Registering viewsets with specific URL prefixes and basenames
router.register('users', UserViewSet, basename='user')  # URL: /users/ (for listing, creating users)
router.register('addresses', AddressViewSet, basename='address')  # URL: /addresses/ (for listing, managing addresses)
router.register('physical-addresses', PhysicalAddressViewSet, basename='physicaladdress')  # URL: /physical-addresses/ (for listing, managing physical addresses)
router.register('credit-cards', CreditCardViewSet, basename='creditcard')  # URL: /credit-cards/ (for managing credit cards)
router.register(r'chats', ChatViewSet, basename='chat')  # URL: /chats/ (for managing user chats)
router.register(r'messages', MessageViewSet, basename='message')  # URL: /messages/ (for managing chat messages)
router.register(r'all-chats', AllChatsViewSet, basename='all_chats')  # URL: /all-chats/ (for all user chats)

# Define the URL patterns to include JWT token routes and router-generated URLs
urlpatterns = [
    # JWT Token management paths
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),  # Refresh JWT token
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),  # Verify JWT token

    # User authentication paths
    path('login/', LoginView.as_view(), name='login'),  # User login (to authenticate and obtain a JWT)
    path('logout/', CustomLogoutView.as_view(), name='logout'),  # User logout (to invalidate the JWT)

    # OTP paths for generating and verifying One-Time Passwords (extra security layer)
    path('otp/', OTPViewSet.as_view({'post': 'generate_otp'}), name='generate_otp'),  # Generate OTP for user
    path('otp/verify/', OTPViewSet.as_view({'post': 'verify_otp'}), name='verify_otp'),  # Verify OTP provided by user

    # Include all the URLs generated by the router (for viewsets)
    path('', include(router.urls)),  # Include routes for the viewsets above
]
