# Generated by Django 5.0.7 on 2024-08-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicaladdress',
            old_name='address_line_2',
            new_name='street_address2',
        ),
    ]
