# Generated by Django 5.0.7 on 2024-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_rename_address_line_2_physicaladdress_street_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('S', 'Shipping Address'), ('B', 'Billing Address')], max_length=10, null=True),
        ),
    ]
