version: '3.8'

services:
  # Frontend microservice
  usenlease-frontend:
    image: ngumonelson123/frontend-image:latest
    container_name: usenlease-frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - usenlease-backend
    networks:
      - app-net
    env_file:
      - .env

  # Backend microservice
  usenlease-backend:
    image: ngumonelson123/backend-image:latest
    container_name: usenlease-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /home/nelson-ngumo/DevOps07/usenlease/db.sqlite3:/app/db.sqlite3  # Mount the SQLite3 database from your local machine
      - ./backend:/app/backend  # Mount the backend directory only
    networks:
      - app-net
    env_file:
      - .env
    command: |
      bash -c "cd /app/backend && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  # Navigate to backend and run migrations

# Network configuration
networks:
  app-net:
    driver: bridge

# Docker volume for persistent data (optional)
volumes:
  sqlite-data:
    driver: local
