version: "3.8"

services:

  # Frontend microservice
  ngumo-client:
    image: ngumonelson123/frontend-image:latest
    build: ./frontend
    container_name: usenlease-frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - usenlease-backend
    networks:
      - app-net
    env_file:
      - .env  # This references your .env file if you want to inject environment variables for the client

  # Backend microservice
  ngumo-backend:
    image: ngumonelson123/backend-image:latest
    build: ./backend
    container_name: usenlease-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "8000:8000"
    depends_on: 
      - app-ip-mongo
    networks:
      - app-net
    env_file:
      - .env  # This references your .env file if you want to inject environment variables for the backend

  # MongoDB Database microservice
  app-ip-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db
    env_file:
      - .env  # You can add environment variables for MongoDB if required, such as authentication credentials

# Network configuration
networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16 

# Docker volume for persistent data
volumes:
  app-mongo-data:
    driver: local
