version: '3.8'

services:

  # Frontend microservice
  usenlease-frontend:
    build:
      context: ./frontend  # Path to your frontend directory
      dockerfile: Dockerfile # Specify if your Dockerfile is named something else
    image: ngumonelson123/frontend-image:latest
    container_name: usenlease-frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - usenlease-backend
    networks:
      - app-net
    env_file:
      - .env

  # Backend microservice
  usenlease-backend:
    build:
      context: ./backend  # Path to your backend directory
      dockerfile: Dockerfile # Specify if your Dockerfile is named something else
    image: ngumonelson123/backend-image:latest
    container_name: usenlease-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "8000:8000"
    depends_on: 
      - app-ip-mongo
    networks:
      - app-net
    env_file:
      - .env

  # MongoDB Database microservice
  app-ip-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db
    env_file:
      - .env 

# Network configuration
networks:
  app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16 

# Docker volume for persistent data
volumes:
  app-mongo-data:
    driver: local
