# Generated by Django 4.2 on 2024-11-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
