# Generated by Django 4.2 on 2024-12-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_companyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_management.address'),
        ),
    ]
