# Generated by Django 4.2 on 2024-12-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_rename_terms_and_conditions_companyinfo_lesee_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='lessor_terms_and_conditions',
            new_name='lesor_terms_and_conditions',
        ),
    ]
