# Generated by Django 4.2 on 2024-12-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_rename_lessor_terms_and_conditions_companyinfo_lesor_terms_and_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='lesor_terms_and_conditions',
            new_name='lessor_terms_and_conditions',
        ),
    ]
