# Generated by Django 4.2 on 2024-12-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_remove_companyinfo_lesee_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='lessee_terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='lessor_terms_and_conditions',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='terms_and_conditions',
            field=models.TextField(default='tems', verbose_name='Terms and Conditions'),
            preserve_default=False,
        ),
    ]
