# Generated by Django 4.2 on 2024-12-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_remove_companyinfo_lessee_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['created_at'],
            },
        ),
    ]
