apiVersion: apps/v1
kind: Deployment
metadata:
  name: usenlease-deployment
  namespace: usenlease
  labels:
    app: usenlease-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usenlease-app
  template:
    metadata:
      labels:
        app: usenlease-app
    spec:
      containers:
        - name: combined-images
          image: ngumonelson123/combined-image:v1.2.36
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: usenlease-config
            - secretRef:
                name: usenlease-secrets
          # livenessProbe:
          #   httpGet:
          #     path: /healthz/
          #     port: 8000
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          #   failureThreshold: 6
          # readinessProbe:
          #  httpGet:
          #    path: /healthz/
          #    port: 8000
          #  initialDelaySeconds: 30
          #  periodSeconds: 5
          #  failureThreshold: 6
