# Generated by Django 4.2 on 2024-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0006_alter_cartitem_quantity_alter_cartitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
