# Generated by Django 4.2 on 2024-12-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0009_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
