# Generated by Django 4.2 on 2024-12-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0010_equipment_is_featured_equipment_is_trending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
    ]
