# Generated by Django 4.2 on 2024-12-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='terms',
            field=models.TextField(default='Use the items for the correct purpose.'),
        ),
    ]
