# Generated by Django 5.0.7 on 2024-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default='lyfcuyhc3rey0ay4kb9xwuwmatu30a6x', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
