# Generated by Django 5.0.7 on 2024-08-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0003_alter_cartitem_cart_alter_order_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
