# Generated by Django 5.0.7 on 2024-08-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0007_alter_equipment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
