name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  IMAGE: ngumonelson123/combined-image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=v1.2.${{ github.run_number }}
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
        
        docker build --build-arg SECRET_KEY=django-insecure-xyz123 \
        -t $IMAGE:$IMAGE_TAG \
        -t $IMAGE:latest .

       
        docker push $IMAGE:$IMAGE_TAG
        docker push $IMAGE:latest

    - name: Update Kubernetes Manifests
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        
        git config --global user.email "ci@usenlease.dev"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/Denislive/usenlease.git
        sed -i "s|image: $IMAGE:.*|image: $IMAGE:${{ env.IMAGE_TAG }}|" k8s/usenlease-deployment.yaml
        git add k8s/
        git commit -m "Update image to $IMAGE:${{ env.IMAGE_TAG }} [skip ci]"
        git push

   #Deploy to Heroku
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
        docker tag $IMAGE:${{ env.IMAGE_TAG }} registry.heroku.com/$HEROKU_APP_NAME/web
        docker push registry.heroku.com/$HEROKU_APP_NAME/web
        heroku container:release web --app $HEROKU_APP_NAME

    #HCP Terraform: Let Terraform Cloud handle plan/apply automatically
    #Triggered by any `.tf` changes in `iac/` folder

    - name: Send Slack notification on success
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"✅ CI/CD Success: Build #${{ github.run_number }} pushed Docker image and updated manifests to ArgoCD. Image: $IMAGE:${{ env.IMAGE_TAG }}\"
        }" ${{ secrets.SLACK_WEBHOOK }}

    - name: Send Slack notification on failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"❌ CI/CD Failed: Build #${{ github.run_number }} failed. Check GitHub logs.\"
        }" ${{ secrets.SLACK_WEBHOOK }}
