name: Sync to GitLab
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Add GitLab remote
        run: |
          git remote remove gitlab || true  # Remove existing remote if it exists
          git remote add gitlab git@gitlab.com:Ngumonelson123/usenlease.git

      - name: Pull from GitLab
        run: |
          git pull gitlab master --rebase  # Pull and rebase changes from GitLab

      - name: Push to GitLab
        run: |
          git push gitlab master
