name: Sync to GitLab
on:
  push:
    branches:
      - master  # Replace with your default branch name if it's not 'master'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Add GitLab remote
        run: |
          git remote remove gitlab || true  # Remove existing remote if it exists
          git remote add gitlab git@gitlab.com:Ngumonelson123/usenlease.git

      - name: Pull and rebase from GitLab
        run: |
          git fetch gitlab master  # Fetch the latest changes from GitLab
          git rebase gitlab/master  # Rebase local changes on top of GitLab's master
          # Resolve conflicts (if any)
          if git status | grep -q "both added"; then
            echo "Resolving conflicts..."
            # Automatically keep local changes for conflicting files
            git checkout --ours .
            git add .
            git rebase --continue
          fi

      - name: Push to GitLab
        run: |
          git push gitlab master --force-with-lease  # Force-push with lease